"""Regenerate `earthlens/radar/radar_data_catalog.yaml` from the NOAA station table.

The authoritative WSR-88D site list is published by NOAA's Historical
Observing Metadata Repository (HOMR) as a fixed-width text file:

    https://www.ncei.noaa.gov/access/homr/file/nexrad-stations.txt

Each row carries the four-letter `ICAO` id (`KTLX`), `NAME`, two-letter
state `ST`, and `LAT` / `LON` in decimal degrees. This tool fetches that
file, parses the fixed-width columns (column spans are read from the
dashed separator line, so the parser does not hard-code offsets),
filters to rows with a valid four-letter id and finite coordinates, and
rewrites the bundled `radar_data_catalog.yaml` with a `stations:` block
sorted by id. It is the radar analogue of
`tools/nwp/refresh_nwp_catalog.py` / `tools/chc/refresh_chc_catalog.py`.

Run with:

    pixi run -e dev python tools/radar/refresh_radar_catalog.py
    pixi run -e dev python tools/radar/refresh_radar_catalog.py --dry-run
"""

from __future__ import annotations

import argparse
import urllib.request
from pathlib import Path

from earthlens.radar.catalog import CATALOG_PATH

#: NOAA HOMR fixed-width NEXRAD station table.
SOURCE_URL = "https://www.ncei.noaa.gov/access/homr/file/nexrad-stations.txt"


def _column_spans(separator: str) -> dict[str, tuple[int, int]]:
    """Derive `(start, end)` spans from a header / dashed-separator pair.

    Args:
        separator: The line of dash-groups under the header row.

    Returns:
        list[tuple[int, int]]: One `(start, end)` slice per column.
    """
    spans: list[tuple[int, int]] = []
    start: int | None = None
    for i, ch in enumerate(separator):
        if ch == "-" and start is None:
            start = i
        elif ch != "-" and start is not None:
            spans.append((start, i))
            start = None
    if start is not None:
        spans.append((start, len(separator)))
    return spans


def parse_stations(text: str) -> dict[str, dict]:
    """Parse the HOMR table text into `{icao: {name, latitude, longitude, state}}`.

    Args:
        text: The full `nexrad-stations.txt` body.

    Returns:
        dict[str, dict]: One entry per valid WSR-88D site, keyed by ICAO id.
    """
    lines = text.splitlines()
    header, separator = lines[0], lines[1]
    spans = _column_spans(separator)
    cols = [header[s:e].strip() for s, e in spans]
    idx = {name: i for i, name in enumerate(cols)}

    def cell(row: str, name: str) -> str:
        s, e = spans[idx[name]]
        return row[s:e].strip()

    out: dict[str, dict] = {}
    for row in lines[2:]:
        if not row.strip():
            continue
        icao = cell(row, "ICAO")
        if len(icao) != 4 or not icao.isalpha():
            continue
        try:
            lat = float(cell(row, "LAT"))
            lon = float(cell(row, "LON"))
        except ValueError:
            continue
        if not (-90 <= lat <= 90 and -180 <= lon <= 180):
            continue
        out[icao] = {
            "name": cell(row, "NAME").title(),
            "latitude": round(lat, 4),
            "longitude": round(lon, 4),
            "state": cell(row, "ST"),
        }
    return dict(sorted(out.items()))


def render_yaml(stations: dict[str, dict]) -> str:
    """Render the `stations:` YAML block for the catalog file.

    Args:
        stations: The parsed `{icao: row}` mapping.

    Returns:
        str: The full YAML document text.
    """
    lines = [
        "# NEXRAD WSR-88D station registry for earthlens.radar.",
        "#",
        "# Regenerated by tools/radar/refresh_radar_catalog.py from NOAA HOMR",
        f"# ({SOURCE_URL}). Informational: any valid four-letter site id can be",
        "# fetched even if absent here (the volume just gets no point geometry).",
        "",
        "stations:",
    ]
    for icao, row in stations.items():
        name = row["name"].replace('"', "'")
        lines.append(f"  {icao}:")
        lines.append(f'    name: "{name}"')
        lines.append(f"    latitude: {row['latitude']}")
        lines.append(f"    longitude: {row['longitude']}")
        lines.append(f'    state: "{row["state"]}"')
    return "\n".join(lines) + "\n"


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--dry-run", action="store_true", help="print a summary, do not write"
    )
    parser.add_argument(
        "--output", type=Path, default=CATALOG_PATH, help="target YAML path"
    )
    args = parser.parse_args()

    with urllib.request.urlopen(SOURCE_URL, timeout=60) as resp:  # noqa: S310 - https
        text = resp.read().decode("latin-1", "replace")
    stations = parse_stations(text)
    print(f"parsed {len(stations)} WSR-88D sites from {SOURCE_URL}")
    if args.dry_run:
        sample = list(stations.items())[:3]
        for icao, row in sample:
            print(f"  {icao}: {row}")
        return
    args.output.write_text(render_yaml(stations), encoding="utf-8")
    print(f"wrote {args.output} ({len(stations)} stations)")


if __name__ == "__main__":
    main()
