"""Maintain the bundled Earthdata catalog (`src/earthlens/earthdata/`).

An ``argparse`` subcommand CLI — the CMR analog of
``tools/gee/refresh_gee_catalog.py`` (C7). Run with no args for help:

    pixi run -e dev python tools/earthdata/refresh_earthdata_catalog.py --help

Subcommands:

* ``refresh`` — walk CMR per provider (``earthaccess.search_datasets``)
  and rewrite the ``available_datasets:`` block in
  ``catalog/_index.yaml`` in place. ``--limit N`` caps the collections
  fetched per provider (the full long tail is large).
* ``add-dataset <key> <short_name> <version> --provider <code>`` — fetch
  a collection's metadata, infer ``output_kind`` / ``format`` (seeded,
  vet by hand), and print a ready-to-paste ``datasets:`` stanza for the
  per-DAAC file. Reloads the catalog at the end so a broken stanza fails
  the run.

Requires the ``earthdata`` extra (``earthaccess``; Python >=3.12) for
the live subcommands. Exits 0 on success, 1 on any HTTP / parse error.
Not part of the installed package.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

sys.path.insert(0, str(Path(__file__).parent))
from _earthdata_cmr import (  # noqa: E402
    CATALOG_DIR,
    format_from_extension,
    infer_output_kind,
    read_providers,
)


def _load_earthaccess():
    """Import earthaccess or exit with a friendly message."""
    try:
        import earthaccess
    except ImportError:
        sys.exit(
            "earthaccess is required for live CMR queries; install "
            "`pip install earthlens[earthdata]` (Python >=3.12)."
        )
    return earthaccess


def _collection_short_name(collection: Any) -> str:
    """Best-effort extraction of a collection's short name from CMR UMM."""
    try:
        return collection["umm"]["ShortName"]
    except (KeyError, TypeError):
        return str(getattr(collection, "concept_id", lambda: "")() or collection)


def refresh(args: argparse.Namespace) -> int:
    """Rebuild `available_datasets:` in `_index.yaml` from a CMR walk."""
    earthaccess = _load_earthaccess()
    providers = read_providers()
    found: list[str] = []
    for code in sorted(providers):
        collections = earthaccess.search_datasets(provider=code, count=args.limit)
        names = sorted({_collection_short_name(c) for c in collections})
        found.extend(names)
        print(f"{code}: {len(names)} collections", file=sys.stderr)

    index_path = CATALOG_DIR / "_index.yaml"
    index_path.write_text(
        "# Auto-generated by tools/earthdata/refresh_earthdata_catalog.py.\n"
        + yaml.safe_dump(
            {"available_datasets": sorted(set(found))},
            sort_keys=False,
            allow_unicode=True,
        ),
        encoding="utf-8",
    )
    print(f"wrote {len(set(found))} ids -> {index_path}")
    return 0


def add_dataset(args: argparse.Namespace) -> int:
    """Print a curated `datasets:` stanza for one collection."""
    earthaccess = _load_earthaccess()
    results = earthaccess.search_datasets(
        short_name=args.short_name, version=args.version, count=1
    )
    title = ""
    fmt = ""
    if results:
        umm = results[0].get("umm", {}) if hasattr(results[0], "get") else {}
        title = umm.get("EntryTitle", "")
        formats = umm.get("ArchiveAndDistributionInformation", {})
        fmt = format_from_extension(str(formats)) or ""
    output_kind = infer_output_kind(args.short_name, fmt, title)

    stanza = {
        args.key: {
            "short_name": args.short_name,
            "version": args.version,
            "daac": args.daac or args.provider,
            "provider": args.provider,
            "cadence": "irregular",
            "format": fmt or "unknown",
            "output_kind": output_kind,
            "cloud_hosted": args.cloud_hosted,
            "requires_harmony_for_subset": False,
            "supports_harmony": False,
        }
    }
    print("# add to the matching catalog/<daac>.yaml under datasets:")
    print(yaml.safe_dump({"datasets": stanza}, sort_keys=False, allow_unicode=True))

    sys.path.insert(0, str(CATALOG_DIR.parents[2]))
    from earthlens.earthdata import Catalog  # noqa: E402

    Catalog.load()  # fail loud if the existing catalog is broken
    return 0


def main(argv: list[str] | None = None) -> int:
    """Parse args and dispatch the requested subcommand."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)

    p_refresh = sub.add_parser("refresh", help="rebuild available_datasets index")
    p_refresh.add_argument("--limit", type=int, default=2000)
    p_refresh.set_defaults(func=refresh)

    p_add = sub.add_parser("add-dataset", help="emit a curated stanza for a collection")
    p_add.add_argument("key")
    p_add.add_argument("short_name")
    p_add.add_argument("version")
    p_add.add_argument("--provider", required=True)
    p_add.add_argument("--daac", default="")
    p_add.add_argument("--cloud-hosted", action="store_true", dest="cloud_hosted")
    p_add.set_defaults(func=add_dataset)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
