"""Catalog-tooling handlers for the HDX (Humanitarian Data Exchange) backend.

Registered with core's catalog-tooling commands through the `earthlens.cli`
entry-point group (see `earthlens._hazards_cli`). Everything is public CKAN
(anonymous): `refresher` lists dataset names, `writer` rewrites the gzipped
`_available.json.gz` sidecar merge-preservingly, `prober` reads a dataset's
resources, and `emitter` seeds a curated row from a dataset's resource formats.
"""

from __future__ import annotations

import gzip
import json
from typing import Any

from earthlens.cli.toolkit import (
    BackendInfo,
    curated_attr_ids,
    flatten,
    get_json,
    index_path,
)

_PACKAGE_LIST_URL = "https://data.humdata.org/api/3/action/package_list"
_PACKAGE_SHOW_URL = "https://data.humdata.org/api/3/action/package_show"

#: CKAN resource-format labels mapped to the pyramids output kind.
_VECTOR = {"geopackage", "shp", "geojson", "kml", "geodatabase", "topojson"}
_RASTER = {"geotiff", "cog", "netcdf", "grib", "img", "ascii grid"}
_TABULAR = {"csv", "xlsx", "xls", "json", "tsv", "parquet"}

#: Curated-id resolver over each row's `hdx_id` (the `audit` drift axis).
curated_ids = curated_attr_ids("hdx_id")


def refresher(catalog: Any) -> dict[str, list[str]]:
    """List every HDX (CKAN) dataset name, live (public, anonymous).

    Args:
        catalog: The loaded HDX `Catalog` (unused; the endpoint is fixed).

    Returns:
        A single-group mapping `{"hdx": [sorted dataset names]}`.
    """
    body = get_json(_PACKAGE_LIST_URL)
    return {"hdx": sorted(str(name) for name in body.get("result", []))}


def writer(info: BackendInfo, grouped: dict[str, list[str]]) -> str:
    """Rewrite HDX's gzipped `_available.json.gz` index, merge-preserving.

    The live CKAN `package_list` returns only dataset *names*, whereas the
    sidecar carries an `{org, title}` row per name. To avoid discarding that
    metadata, surviving names keep their existing row and only genuinely-new
    names get a bare row; names gone upstream are dropped. (Full `org`/`title`
    enrichment for new names still belongs to `tools/hdx/refresh_hdx_catalog.py`,
    which fetches `package_show`.)

    Args:
        info: The HDX backend.
        grouped: Group name -> live dataset names (see `refresher`).

    Returns:
        The path of the sidecar rewritten.
    """
    path = index_path(info).parent / "_available.json.gz"
    try:
        with gzip.open(path, "rt", encoding="utf-8") as handle:
            previous = json.load(handle).get("datasets", {})
    except FileNotFoundError:
        previous = {}
    datasets = {
        name: previous.get(name, {"org": "", "title": ""}) for name in flatten(grouped)
    }
    payload = {
        "__comment__": "AUTO-GENERATED by `earthlens datasets refresh hdx --write`. "
        "Every HDX dataset id with its org/title; new ids carry empty "
        "org/title until enriched by tools/hdx/refresh_hdx_catalog.py.",
        "datasets": datasets,
    }
    with gzip.open(path, "wt", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=1)
    return str(path)


def prober(catalog: Any, dataset: str) -> dict[str, dict[str, Any]]:
    """Probe an HDX dataset's resources (files) via public CKAN package_show.

    HDX datasets are file bundles rather than band/variable rasters, so the
    "schema" is the resource list — each downloadable file and its format.

    Args:
        catalog: The loaded HDX `Catalog` (resolves a key's `hdx_id`).
        dataset: A curated key or a CKAN dataset name.

    Returns:
        Mapping of resource (file) name to `{format}`.
    """
    record = catalog.datasets.get(dataset)
    hdx_id = getattr(record, "hdx_id", None) or dataset
    body = get_json(_PACKAGE_SHOW_URL, params={"id": hdx_id})
    resources = (body.get("result") or {}).get("resources", [])
    schema: dict[str, dict[str, Any]] = {}
    for resource in resources:
        name = resource.get("name")
        if name:
            schema[str(name)] = {"format": resource.get("format")}
    return schema


def _kind_for_format(fmt: str) -> str | None:
    """Return the pyramids output kind for a CKAN format label (or None)."""
    token = fmt.strip().lower()
    if token in _VECTOR:
        return "vector"
    if token in _RASTER:
        return "raster"
    if token in _TABULAR:
        return "tabular"
    return None


def _package(hdx_id: str) -> dict[str, Any]:
    """Return one HDX dataset's CKAN package_show result (public)."""
    body = get_json(_PACKAGE_SHOW_URL, params={"id": hdx_id})
    return body.get("result") or {}


def emitter(catalog: Any, upstream_id: str, **opts: Any) -> dict[str, Any]:
    """Seed an HDX `datasets:` row from a dataset's CKAN resources.

    Args:
        catalog: The loaded HDX `Catalog` (unused; CKAN is the source).
        upstream_id: The HDX dataset id (CKAN name).
        **opts: Unused.

    Returns:
        The seeded row (formats / themes / output_kinds inferred from the
        dataset's resource formats).
    """
    package = _package(upstream_id)
    organisation = package.get("organization")
    org_name = organisation.get("name", "") if isinstance(organisation, dict) else ""
    formats = sorted(
        {r["format"] for r in package.get("resources", []) if r.get("format")}
    )
    kinds = sorted({k for k in (_kind_for_format(f) for f in formats) if k})
    return {
        "hdx_id": upstream_id,
        "org": org_name,
        "title": package.get("title", ""),
        "themes": kinds or ["unknown"],
        "formats": formats,
        "resource_filter": "",
        "output_kinds": kinds or ["tabular"],
    }
