"""Server catalog loader for the generic ERDDAP backend.

Hosts :class:`Catalog`, the pydantic-backed reader for the bundled
multi-server ERDDAP catalog. ERDDAP is a protocol spoken by hundreds of
independent servers, so the catalog is a curated map of concrete
`(server_url, dataset_id, protocol)` rows rather than one provider's
dataset list. It ships as a sharded directory of per-slice YAML files at
`src/earthlens/erddap/catalog/` (`coral-reef-watch.yaml`,
`coastwatch.yaml`, …) plus a single `_index.yaml` carrying the
informational `available_datasets:` list, mirroring the
:mod:`earthlens.cmems.catalog` layout. Each per-slice file contributes
its `datasets:` block; the loader unions them into one :class:`Catalog`
at construction time.

A `dataset=<id>` request resolves to a :class:`Dataset` via
:meth:`Catalog.get` (a thin wrapper over the shared
:meth:`~earthlens.base.AbstractCatalog.get_dataset` did-you-mean
lookup). The row's `protocol` decides the backend's per-instance output
shape: `griddap` → raster NetCDF, `tabledap` → tabular `DataFrame`.

The path to the bundled catalog directory lives at
:data:`CATALOG_PATH`; tests can monkey-patch that module attribute to
redirect the loader at a temporary directory or single YAML file.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Literal, cast

from pydantic import BaseModel, ConfigDict, Field, ValidationError

from earthlens.base import AbstractCatalog
from earthlens.base.catalog_source import (
    catalog_cache_key,
    yaml_files_for,
)
from earthlens.base.yaml_loader import CatalogParseCache, load_yaml_strict

CATALOG_PATH: Path = Path(__file__).parent / "catalog"

#: The two ERDDAP request protocols. `griddap` returns gridded fields
#: (raster NetCDF); `tabledap` returns record tables (a `DataFrame`).
ProtocolLiteral = Literal["griddap", "tabledap"]

#: Default grid dimension order for a griddap dataset when the catalog
#: row omits `dim_names`. Covers the common `[time, latitude, longitude]`
#: cube; rows whose grids add an `altitude` / `depth` axis must list it.
_DEFAULT_DIM_NAMES: tuple[str, ...] = ("time", "latitude", "longitude")

# Module-level cache of parsed catalog data, keyed on the resolved path
# plus a tuple of `(file, mtime_ns)` for every YAML the load touched, so
# editing any per-slice file invalidates the entry without inspecting
# every row. Mirrors the CMEMS multi-file pattern.
_CATALOG_CACHE: dict[Any, tuple[list[str], dict[str, Dataset]]] = CatalogParseCache()


def clear_catalog_cache() -> None:
    """Empty the module-level catalog parse cache.

    Useful in tests that rewrite the catalog on disk and want to force a
    re-parse. Production callers do not need this — the cache keys
    include every contributing file's `st_mtime_ns`, so any real file
    mutation invalidates the entry on its own.
    """
    _CATALOG_CACHE.clear()


def _yaml_files_for(path: Path) -> list[Path]:
    """Return the sorted YAML files contributing to a load.

    Binds the shared `yaml_files_for` to this catalog's provider label. Kept
    as a module-level name because the tests import and monkey-patch it.
    """
    return yaml_files_for(path, provider='ERDDAP', shard_noun='per-slice')


def _load_catalog_data(path: Path) -> tuple[list[str], dict[str, Dataset]]:
    """Parse, validate, and cache the ERDDAP catalog at `path`.

    When `path` is a directory, every `*.yaml` file is merged: a dataset
    key declared in two files is an error, and every curated key must
    appear in the merged `available_datasets:` index (when one is
    present). Cached on the resolved path plus every contributing file's
    `mtime_ns`, so a second `Catalog()` on an unchanged tree skips both
    YAML parsing and pydantic validation.

    Args:
        path: Catalog directory (default `src/earthlens/erddap/catalog/`)
            or a single `*.yaml` file.

    Returns:
        A `(available_datasets, datasets)` tuple — the merged informational
        `available_datasets:` index (every id the curated servers publish,
        regenerated by `earthlens datasets refresh erddap --write`) and the
        curated `datasets:` map.

    Raises:
        ValueError: If no file has a `datasets:` block, a dataset key is
            declared in two files, a row fails validation, or a curated
            key is absent from `available_datasets:`.
    """
    files = _yaml_files_for(path)
    key = catalog_cache_key(path, files)
    cached = _CATALOG_CACHE.get(key)
    if cached is not None:
        return cached

    merged_available: list[str] = []
    merged_rows: dict[str, Any] = {}
    origin: dict[str, Path] = {}
    for file_path in files:
        data = load_yaml_strict(file_path) or {}
        merged_available.extend(data.get("available_datasets") or [])
        for ds_id, ds_body in (data.get("datasets") or {}).items():
            if ds_id in merged_rows:
                raise ValueError(
                    f"dataset {ds_id!r} declared in two catalog files: "
                    f"{origin[ds_id]} and {file_path}"
                )
            merged_rows[ds_id] = ds_body
            origin[ds_id] = file_path

    if not merged_rows:
        raise ValueError(
            f"{path} is missing or has an empty 'datasets:' block. The "
            "catalog must contain at least one dataset row."
        )

    available = set(merged_available)
    datasets: dict[str, Dataset] = {}
    for ds_id, ds_body in merged_rows.items():
        payload = dict(ds_body or {})
        payload.setdefault("dataset_id", ds_id)
        try:
            datasets[ds_id] = Dataset(**payload)
        except ValidationError as exc:
            raise ValueError(
                f"{origin[ds_id]} dataset {ds_id!r} failed validation:\n{exc}"
            ) from exc
        if available and ds_id not in available:
            raise ValueError(
                f"dataset {ds_id!r} is in 'datasets:' but missing from "
                f"'available_datasets:' ({origin[ds_id]}); add it to "
                "_index.yaml too."
            )

    _CATALOG_CACHE[key] = (sorted(available), datasets)
    return _CATALOG_CACHE[key]


class Dataset(BaseModel):
    """One curated ERDDAP dataset pinned to a concrete server.

    Mirrors a single `datasets.<dataset_id>:` block in one of the
    per-slice `catalog/*.yaml` files. The block key is the ERDDAP
    `dataset_id`; it is echoed into :attr:`dataset_id` by the loader so
    the row is self-describing.

    Attributes:
        server_url: Base URL of the ERDDAP server (no trailing slash),
            e.g. `"https://coastwatch.pfeg.noaa.gov/erddap"`.
        dataset_id: The dataset id on that server (the key under
            `datasets:`).
        protocol: `"griddap"` (gridded raster output) or `"tabledap"`
            (tabular `DataFrame` output). Decides the backend's
            per-instance `OUTPUT_KIND`.
        variables: Default variable set requested when the caller passes
            no `variables=`. For griddap these are grid variable names
            (e.g. `"CRW_SSTANOMALY"`); for tabledap, table column names.
        dim_names: Grid dimension order for a griddap request (e.g.
            `["time", "latitude", "longitude"]`). Ignored for tabledap.
        flux_variables: Subset of griddap `variables` that are
            accumulations / fluxes rather than instantaneous state fields.
            The backend marks these `is_flux=True` so an `aggregate=` with
            `op="auto"` reduces them by `"sum"` (the window total) instead
            of `"mean"`. Empty by default — ERDDAP griddap variables are
            overwhelmingly state fields (SST anomaly, DHW, chlorophyll).
        lon_360: The server stores longitude in the `[0, 360]` convention
            rather than the framework's `[-180, 180]`. Set `True` for a
            **tabledap** row on such a server (e.g. the UHSLC tide gauges)
            so the backend shifts the request's longitude bounds; a
            `[-180, 180]` bound would otherwise match no rows. No effect on
            griddap rows.
        title: Human-readable description used in log messages.
        license_note: Licence / attribution note for the dataset.

    Examples:
        - Inspect a curated griddap row:

            ```python
            >>> from earthlens.erddap import Catalog
            >>> ds = Catalog().get("NOAA_DHW")
            >>> ds.protocol
            'griddap'
            >>> ds.server_url.endswith("/erddap")
            True

            ```
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    server_url: str
    dataset_id: str
    protocol: ProtocolLiteral
    variables: list[str] = Field(default_factory=list)
    dim_names: list[str] = Field(default_factory=lambda: list(_DEFAULT_DIM_NAMES))
    flux_variables: list[str] = Field(default_factory=list)
    lon_360: bool = False
    title: str = ""
    license_note: str = ""


class Catalog(AbstractCatalog):
    """Server catalog for the generic ERDDAP backend.

    Reads the bundled `catalog/` directory (shipped as package data) and
    exposes its curated rows as a typed `datasets` map. Instantiate with
    no arguments (`Catalog()`) — :func:`model_post_init` parses the YAML
    and populates every field in one pass through a `(path, mtime)`-keyed
    cache.

    Attributes:
        available_datasets: Informational index of every dataset id the
            curated ERDDAP servers publish (the merged `available_datasets:`
            block from `catalog/_index.yaml`, regenerated by `earthlens
            datasets refresh erddap --write`). Every curated `datasets` key
            is a member of it (the loader enforces the subset). Runtime
            download code does not consume it; the `datasets` map is the
            curated subset that carries the per-dataset request metadata.
        datasets: Structural map keyed by ERDDAP dataset id; each value
            is a :class:`Dataset` row.

    Examples:
        - Resolve a dataset and read its protocol:

            ```python
            >>> from earthlens.erddap import Catalog
            >>> Catalog().get("cwwcNDBCMet").protocol
            'tabledap'

            ```
    """

    _catalog_kind: str = "ERDDAP catalog"

    available_datasets: list[str] = Field(default_factory=list)
    datasets: dict[str, Dataset] = Field(default_factory=dict)

    @classmethod
    def _autoload(cls) -> dict[str, Any]:
        """Read the bundled catalog from disk.

        Returns:
            dict[str, Any]: The `available_datasets`, `datasets` read from
                the bundled catalog.
        """
        loaded = Catalog.load()
        return {
            "available_datasets": loaded.available_datasets,
            "datasets": loaded.datasets,
        }

    @classmethod
    def load(cls, catalog_path: Path | None = None) -> Catalog:
        """Read the ERDDAP catalog from disk (cached).

        Args:
            catalog_path: Path to the `catalog/` directory or a single
                `*.yaml` file. Defaults to module-level
                :data:`CATALOG_PATH`.

        Returns:
            A fully-populated :class:`Catalog`.

        Raises:
            ValueError: Propagated from :func:`_load_catalog_data`.
        """
        catalog_path = catalog_path if catalog_path is not None else CATALOG_PATH
        available_datasets, datasets = _load_catalog_data(catalog_path)
        # Fall back to the curated keys when no `available_datasets:` index is
        # present (e.g. a single-file catalog monkey-patched in tests), so the
        # `curated ⊆ available` invariant always holds.
        return cls(
            available_datasets=list(available_datasets) or sorted(datasets),
            datasets=dict(datasets),
        )

    def get(self, dataset_id: str) -> Dataset:
        """Return the :class:`Dataset` row for `dataset_id`.

        Thin typed wrapper over the shared
        :meth:`~earthlens.base.AbstractCatalog.get_dataset`, which raises
        `ValueError` with a did-you-mean hint on an unknown id.

        Args:
            dataset_id: ERDDAP dataset id as it appears as a key in
                :attr:`datasets` (e.g. `"NOAA_DHW"`).

        Returns:
            Dataset: The curated row.

        Raises:
            ValueError: If `dataset_id` is not curated (message lists a
                close match).

        Examples:
            - Unknown id raises with a hint:

                ```python
                >>> from earthlens.erddap import Catalog
                >>> try:
                ...     Catalog().get("NOAA_DHX")
                ... except ValueError as exc:
                ...     print("ERDDAP catalog" in str(exc) and "NOAA_DHW" in str(exc))
                True

                ```
        """
        return cast("Dataset", self.get_dataset(dataset_id))
