"""Maintain the bundled openEO catalog index (`src/earthlens/openeo/catalog/_index.yaml`).

A small `argparse` CLI — the direct analogue of `tools/gee/refresh_gee_catalog.py`
and `tools/stac/refresh_stac_catalog.py` — that lists the openEO backend's
collections and processes and rewrites the informational `available_collections:`
/ `available_processes:` index in place. Listing collections and processes is
**anonymous** (no OIDC login needed), so the refresh runs without credentials.

Run with no args to see the subcommand list:

    python tools/openeo/refresh_openeo_catalog.py --help

Subcommands:

* `refresh` — connect to the endpoint (default CDSE core), call
  `Connection.list_collections()` + `list_processes()`, and rewrite both index
  lists in `_index.yaml`. `--dry-run` prints the regenerated file instead of
  writing it.
* `validate-recipe <key>` — check a curated recipe's `base_collection` is a live
  collection and every process its graph names is a live process; exit non-zero
  on any drift.

The curated `collections:` / `recipes:` blocks are **not** touched — per-row
curation is hand review. Exits 0 on success, 1 on any HTTP / parse / drift error.
Not part of the installed package.
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

import yaml

CATALOG_INDEX_PATH = Path("src/earthlens/openeo/catalog/_index.yaml")
DEFAULT_ENDPOINT = "https://openeo.dataspace.copernicus.eu"


def _connect(endpoint: str, *, verbose: bool = False):
    """Open an (unauthenticated) openEO connection for listing.

    Args:
        endpoint: openEO API root URL.
        verbose: When `True`, print progress to stderr.

    Returns:
        An `openeo.Connection`.

    Raises:
        RuntimeError: When the endpoint cannot be reached.
    """
    import openeo

    if verbose:
        print(f"  connecting to {endpoint}", file=sys.stderr)
    try:
        return openeo.connect(endpoint)
    except Exception as exc:  # noqa: BLE001 - re-raise with endpoint context
        raise RuntimeError(f"failed to connect to {endpoint}: {exc}") from exc


def _list_ids(connection, kind: str) -> list[str]:
    """Return the sorted ids of a listing endpoint (`collections` / `processes`).

    Args:
        connection: An open `openeo.Connection`.
        kind: `"collections"` or `"processes"`.

    Returns:
        The sorted id strings.

    Raises:
        RuntimeError: When the listing call fails.
    """
    lister = getattr(connection, f"list_{kind}")
    try:
        return sorted(entry["id"] for entry in lister())
    except Exception as exc:  # noqa: BLE001 - re-raise with context
        raise RuntimeError(f"failed to list {kind}: {exc}") from exc


def _render_index(
    collections: list[str], processes: list[str], endpoint: str
) -> str:
    """Render the full `_index.yaml` text (header comment + both lists).

    Args:
        collections: Sorted collection ids.
        processes: Sorted process ids.
        endpoint: The endpoint the index was refreshed from (for the header).

    Returns:
        The YAML text (newline-terminated).
    """
    import openeo

    header = (
        "# Informational index of every collection and process the default CDSE openEO\n"
        f"# backend ({endpoint}) advertises. Regenerated by\n"
        "# tools/openeo/refresh_openeo_catalog.py. Not a curated list -- the curated\n"
        "# collections/recipes live in collections.yaml / recipes.yaml.\n"
        f"# Last refreshed: {dt.date.today().isoformat()} "
        f"(openeo client {openeo.__version__}).\n"
    )
    body = yaml.safe_dump(
        {"available_collections": collections, "available_processes": processes},
        default_flow_style=False,
        sort_keys=False,
        width=100,
    )
    return header + body


def _cmd_refresh(args: argparse.Namespace) -> int:
    """List collections + processes and rewrite the index.

    Args:
        args: Parsed CLI args (`catalog_index`, `endpoint`, `dry_run`, `verbose`).

    Returns:
        Process exit code (0 success, 1 on any failure).
    """
    from earthlens.openeo.catalog import Catalog

    try:
        connection = _connect(args.endpoint, verbose=args.verbose)
        collections = _list_ids(connection, "collections")
        processes = _list_ids(connection, "processes")
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print(
        f"found {len(collections)} collections, {len(processes)} processes",
        file=sys.stderr,
    )
    new_text = _render_index(collections, processes, args.endpoint)
    if args.dry_run:
        print(new_text)
        return 0
    args.catalog_index.write_text(new_text, encoding="utf-8")
    print(f"wrote {args.catalog_index}", file=sys.stderr)
    Catalog.load(args.catalog_index.parent)  # reload so a broken write fails loud
    return 0


def _cmd_validate_recipe(args: argparse.Namespace) -> int:
    """Check a recipe's base collection + process names exist live.

    Args:
        args: Parsed CLI args (`recipe`, `endpoint`, `verbose`).

    Returns:
        Process exit code (0 when the recipe is consistent, 1 on drift/error).
    """
    from earthlens.openeo.catalog import Catalog

    catalog = Catalog()
    try:
        recipe = catalog.get_recipe(args.recipe)
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    try:
        connection = _connect(args.endpoint, verbose=args.verbose)
        live_collections = set(_list_ids(connection, "collections"))
        live_processes = set(_list_ids(connection, "processes"))
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    problems: list[str] = []
    if recipe.base_collection not in live_collections:
        problems.append(
            f"base_collection {recipe.base_collection!r} not served by the backend"
        )
    for step in recipe.graph:
        process_name = next(iter(step))
        if process_name not in live_processes:
            problems.append(f"process {process_name!r} not advertised by the backend")

    if problems:
        print(f"recipe {args.recipe!r} has drift:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1
    print(f"recipe {args.recipe!r} is consistent with {args.endpoint}", file=sys.stderr)
    return 0


def main(argv: list[str] | None = None) -> int:
    """CLI entry point.

    Args:
        argv: Argument vector (defaults to `sys.argv[1:]`).

    Returns:
        Process exit code.
    """
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_refresh = sub.add_parser(
        "refresh", help="list collections + processes and rewrite _index.yaml"
    )
    p_refresh.add_argument(
        "--catalog-index", type=Path, default=CATALOG_INDEX_PATH,
        help="path to catalog/_index.yaml",
    )
    p_refresh.add_argument(
        "--endpoint", default=DEFAULT_ENDPOINT, help="openEO API root URL"
    )
    p_refresh.add_argument(
        "--dry-run", action="store_true",
        help="print the regenerated index instead of writing it",
    )
    p_refresh.add_argument("-v", "--verbose", action="store_true", help="print progress")
    p_refresh.set_defaults(func=_cmd_refresh)

    p_validate = sub.add_parser(
        "validate-recipe", help="check a recipe's collection + processes exist live"
    )
    p_validate.add_argument("recipe", help="curated recipe key to validate")
    p_validate.add_argument(
        "--endpoint", default=DEFAULT_ENDPOINT, help="openEO API root URL"
    )
    p_validate.add_argument("-v", "--verbose", action="store_true", help="print progress")
    p_validate.set_defaults(func=_cmd_validate_recipe)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
